source 'https://www.rubygems.org'
gem 'rake'
gem 'rack-flash3'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sqlite3'
gem 'activerecord'
gem 'thin'

source 'http://gemcutter.org'
gem 'sinatra-activerecord'
